[package]
name = "flick-flasher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["cargo", "derive"] }
env_logger = "0.9"
pixels = "0.9"
wgpu = "0.12"
winit = "0.26"
